set(OSM_APPLICATION_SOURCES
    src/main.cpp

    src/abstract/data.cpp
    src/abstract/data.h
    src/abstract/levelsdata.cpp
    src/abstract/levelsdata.h
    src/abstract/source.cpp
    src/abstract/source.h

    src/audio/client.cpp
    src/audio/client.h
    src/audio/deviceinfo.cpp
    src/audio/deviceinfo.h
    src/audio/devicemodel.cpp
    src/audio/devicemodel.h
    src/audio/format.cpp
    src/audio/format.h
    src/audio/plugin.cpp
    src/audio/plugin.h
    src/audio/stream.cpp
    src/audio/stream.h

    src/chart/axis.cpp
    src/chart/axis.h
    src/chart/coherenceplot.cpp
    src/chart/coherenceplot.h
    src/chart/crestfactorplot.cpp
    src/chart/crestfactorplot.h
    src/chart/cursorhelper.cpp
    src/chart/cursorhelper.h
    src/chart/frequencybasedplot.cpp
    src/chart/frequencybasedplot.h
    src/chart/frequencybasedserieshelper.cpp
    src/chart/frequencybasedserieshelper.h
    src/chart/groupdelayplot.cpp
    src/chart/groupdelayplot.h
    src/chart/impulseplot.cpp
    src/chart/impulseplot.h
    src/chart/levelobject.cpp
    src/chart/levelobject.h
    src/chart/levelplot.cpp
    src/chart/levelplot.h
    src/chart/magnitudeplot.cpp
    src/chart/magnitudeplot.h
    src/chart/meterplot.cpp
    src/chart/meterplot.h
    src/chart/nyquistplot.cpp
    src/chart/nyquistplot.h
    src/chart/painteditem.cpp
    src/chart/painteditem.h
    src/chart/palette.cpp
    src/chart/palette.h
    src/chart/phasedelayplot.cpp
    src/chart/phasedelayplot.h
    src/chart/phaseplot.cpp
    src/chart/phaseplot.h
    src/chart/plot.cpp
    src/chart/plot.h
    src/chart/plotpadding.h
    src/chart/rtaplot.cpp
    src/chart/rtaplot.h
    src/chart/seriesesitem.cpp
    src/chart/seriesesitem.h
    src/chart/seriesitem.h
    src/chart/spectrogramplot.cpp
    src/chart/spectrogramplot.h
    src/chart/stepplot.cpp
    src/chart/stepplot.h
    src/chart/type.h
    src/chart/variablechart.cpp
    src/chart/variablechart.h
    src/chart/xyplot.cpp
    src/chart/xyplot.h

    src/common/appearance.cpp
    src/common/appearance.h
    src/common/atomic.h
    src/common/autosaver.cpp
    src/common/autosaver.h
    src/common/logger.cpp
    src/common/logger.h
    src/common/notifier.cpp
    src/common/notifier.h
    src/common/profiler.cpp
    src/common/profiler.h
    src/common/recentfilesmodel.cpp
    src/common/recentfilesmodel.h
    src/common/settings.cpp
    src/common/settings.h
    src/common/wavfile.cpp
    src/common/wavfile.h
    src/common/workingfolder.cpp
    src/common/workingfolder.h

    src/container/array.h
    src/container/circular.h
    src/container/fifo.h

    src/filesystem/dialog.cpp
    src/filesystem/dialog.h
    src/filesystem/dialogPlugin.cpp
    src/filesystem/dialogPlugin.h
    src/filesystem/plugins/widgetdialogplugin.cpp
    src/filesystem/plugins/widgetdialogplugin.h

    src/generator/brownnoise.cpp
    src/generator/brownnoise.h
    src/generator/burstnoise.cpp
    src/generator/burstnoise.h
    src/generator/channelmodel.cpp
    src/generator/channelmodel.h
    src/generator/generator.cpp
    src/generator/generator.h
    src/generator/generatorthread.cpp
    src/generator/generatorthread.h
    src/generator/mlsplus.cpp
    src/generator/mlsplus.h
    src/generator/mnoise.cpp
    src/generator/mnoise.h
    src/generator/musicnoise.cpp
    src/generator/musicnoise.h
    src/generator/outputdevice.cpp
    src/generator/outputdevice.h
    src/generator/pinknoise.cpp
    src/generator/pinknoise.h
    src/generator/sample.h
    src/generator/sinburst.cpp
    src/generator/sinburst.h
    src/generator/sinnoise.cpp
    src/generator/sinnoise.h
    src/generator/sinsweep.cpp
    src/generator/sinsweep.h
    src/generator/wav.cpp
    src/generator/wav.h
    src/generator/whitenoise.cpp
    src/generator/whitenoise.h

    src/inputdevice.cpp
    src/inputdevice.h

    src/math/averaging.cpp
    src/math/averaging.h
    src/math/bandpass.cpp
    src/math/bandpass.h
    src/math/bessellpf.h
    src/math/biquad.cpp
    src/math/biquad.h
    src/math/coherence.cpp
    src/math/coherence.h
    src/math/complex.cpp
    src/math/complex.h
    src/math/deconvolution.cpp
    src/math/deconvolution.h
    src/math/equalloudnesscontour.cpp
    src/math/equalloudnesscontour.h
    src/math/filter.h
    src/math/fouriertransform.cpp
    src/math/fouriertransform.h
    src/math/integration_tree.cpp
    src/math/integration_tree.h
    src/math/leq.cpp
    src/math/leq.h
    src/math/lowpassfilter.cpp
    src/math/lowpassfilter.h
    src/math/meter.cpp
    src/math/meter.h
    src/math/notch.cpp
    src/math/notch.h
    src/math/weighting.cpp
    src/math/weighting.h
    src/math/windowfunction.cpp
    src/math/windowfunction.h

    src/meta/metabase.cpp
    src/meta/metabase.h
    src/meta/metaequalizer.cpp
    src/meta/metaequalizer.h
    src/meta/metafilter.cpp
    src/meta/metafilter.h
    src/meta/metagroup.h
    src/meta/metameasurement.cpp
    src/meta/metameasurement.h
    src/meta/metastored.cpp
    src/meta/metastored.h
    src/meta/metawindowing.cpp
    src/meta/metawindowing.h

    src/model/metertablemodel.cpp
    src/model/metertablemodel.h
    src/model/sourcemodel.cpp
    src/model/sourcemodel.h

    src/remote/generatorremote.cpp
    src/remote/generatorremote.h
    src/remote/item.cpp
    src/remote/item.h
    src/remote/items/groupitem.cpp
    src/remote/items/groupitem.h
    src/remote/items/measurementitem.cpp
    src/remote/items/measurementitem.h
    src/remote/items/storeditem.cpp
    src/remote/items/storeditem.h
    src/remote/network.cpp
    src/remote/network.h
    src/remote/remoteclient.cpp
    src/remote/remoteclient.h
    src/remote/server.cpp
    src/remote/server.h
    src/remote/tcpreciever.cpp
    src/remote/tcpreciever.h

    src/shared/source_shared.cpp
    src/shared/source_shared.h
    src/shared/sourcelist_shared.cpp
    src/shared/sourcelist_shared.h

    src/source/equalizer.cpp
    src/source/equalizer.h
    src/source/filtersource.cpp
    src/source/filtersource.h
    src/source/group.cpp
    src/source/group.h
    src/source/measurement.cpp
    src/source/measurement.h
    src/source/sourcewindowing.cpp
    src/source/sourcewindowing.h
    src/source/standardline.cpp
    src/source/standardline.h
    src/source/stored.cpp
    src/source/stored.h
    src/source/union.cpp
    src/source/union.h

    src/sourcelist.cpp
    src/sourcelist.h
    src/targettrace.cpp
    src/targettrace.h
)
